import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Poke fight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Kodi<span className="text-blue-300">mon</span>
        </h1>

        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          <Link href="/fight">
            <button>New game</button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
